# advmv
# Autogenerated from man page /usr/share/man/man1/advmv.1.gz
complete -c advmv -l backup --description 'make a backup of each existing destination file.'
complete -c advmv -s b --description 'like --backup but does not accept an argument.'
complete -c advmv -s f -l force --description 'do not prompt before overwriting.'
complete -c advmv -s g -l progress-bar --description 'add progress-bar.'
complete -c advmv -s i -l interactive --description 'prompt before overwrite.'
complete -c advmv -s n -l no-clobber --description 'do not overwrite an existing file .'
complete -c advmv -l strip-trailing-slashes --description 'remove any trailing slashes from each SOURCE argument.'
complete -c advmv -s S -l suffix --description 'override the usual backup suffix.'
complete -c advmv -s t -l target-directory --description 'move all SOURCE arguments into DIRECTORY.'
complete -c advmv -s T -l no-target-directory --description 'treat DEST as a normal file.'
complete -c advmv -s u -l update --description 'move only when the SOURCE file is newer than the destination file or when the…'
complete -c advmv -s v -l verbose --description 'explain what is being done.'
complete -c advmv -s Z -l context --description 'set SELinux security context of destination file to default type.'
complete -c advmv -l help --description 'display this help and exit.'
complete -c advmv -l version --description 'output version information and exit .'

