# arch-audit
# Autogenerated from man page /usr/share/man/man1/arch-audit.1.gz
complete -c arch-audit -s q -l quiet --description '.'
complete -c arch-audit -s r -l recursive --description '.'
complete -c arch-audit -s t -l show-testing --description '.'
complete -c arch-audit -s u -l upgradable --description '.'
complete -c arch-audit -s c -l show-cve --description '.'
complete -c arch-audit -s C -l color --description '.'
complete -c arch-audit -s b -l dbpath --description '.'
complete -c arch-audit -s f -l format --description '.'
complete -c arch-audit -l proxy --description '.'
complete -c arch-audit -l source --description '.'
complete -c arch-audit -l sort --description '.'
complete -c arch-audit -s V -l version --description '.'
complete -c arch-audit -s h -l help --description '.'

