# bat
# Autogenerated from man page /usr/share/man/man1/bat.1.gz
complete -c bat -l highlight-line --description 'highlights line 40.'
complete -c bat -l line-range --description 'prints lines 30 to 40.'

