# calfjackhost
# Autogenerated from man page /usr/share/man/man1/calfjackhost.1.gz
complete -c calfjackhost -s c -l client --description 'sets JACK client name (the name calfjackhost uses when registering in JACK).'
complete -c calfjackhost -s i -l input --description 'name prefix for audio inputs.'
complete -c calfjackhost -s o -l output --description 'name prefix for audio outputs.'
complete -c calfjackhost -s m -l midi --description 'name prefix for MIDI inputs.'
complete -c calfjackhost -l connect-midi --description 'automatically connect all MIDI ports to client:port.'
complete -c calfjackhost -s M --description 'automatically connect all MIDI ports to system:midi_capture_n.'
complete -c calfjackhost -s v -l version --description 'prints a version string (calf some. version. number).'
complete -c calfjackhost -s l -l load --description 'Loads the session state from a file.'
complete -c calfjackhost -s s -l state --description 'Loads the session state from a file, if such a file exists.'
complete -c calfjackhost -s L -l list --description 'List all available plug-ins.'
complete -c calfjackhost -s h -s '?' -l help --description 'prints a help text.'
complete -c calfjackhost -s t -l no-tray --description 'disable the tray icon on start.'

