# ccze
# Autogenerated from man page /usr/share/man/man1/ccze.1.gz
complete -c ccze -s a -l argument --description 'Use this option to pass ARGUMENTS to the specified PLUGIN.'
complete -c ccze -s A -l raw-ansi --description 'If one wants to enable raw ANSI color sequences instead of using curses, this…'
complete -c ccze -s c -l color --description 'Set the color of the keyword KEY to COLOR, like one would do in one of the co…'
complete -c ccze -s C -l convert-date --description 'Convert unix timestamp to readable date format (in oops and squid logs, for e…'
complete -c ccze -s F -l rcfile --description 'Read rcfile as a configuration file upon startup, instead of the default ones.'
complete -c ccze -s h -l html --description 'Instead of colorising the input onto the console, output it in HTML format in…'
complete -c ccze -s l -l list-plugins --description 'List all available (loaded) plugins, along with their type and a short descri…'
complete -c ccze -s m -l mode --description 'Change the output mode.  Available modes are curses, ansi and html.'
complete -c ccze -s o -l options --description 'CCZE is able to toggle some of its features with this option.'
complete -c ccze -s p -l plugin --description 'While the default action is to load all plugins (see the Plugins section belo…'
complete -c ccze -s r -l remove-facilty --description 'Syslog-ng puts the facility level before log messages.'
complete -c ccze -l help --description 'Show summary of options and exit.'
complete -c ccze -s V -l version --description 'Show version of program.'

