# chrpath
# Autogenerated from man page /usr/share/man/man1/chrpath.1.gz
complete -c chrpath -s v -l version --description 'Display program version number.'
complete -c chrpath -s d -l delete --description 'Delete current rpath or runpath setting.'
complete -c chrpath -s c -l convert --description 'Convert the rpath setting into a runpath setting.'
complete -c chrpath -o 'r<path>' -l 'replace<path>' --description 'Replace current rpath or runpath setting with the path given.'
complete -c chrpath -s k -l keepgoing --description 'Do not fail on first error, but process all arguments before returning the er…'
complete -c chrpath -s l -l list --description 'List the current rpath or runpath (default).'
complete -c chrpath -s r -l replace --description 'Replace current rpath or runpath setting with the path given.'
complete -c chrpath -s h -l help --description 'Show usage information.  EXIT STATUS.'

