# ctags
# Autogenerated from man page /usr/share/man/man1/ctags.1p.gz
complete -c ctags -o ftagsfile --description 'Write the object locator lists into R tagsfile instead of the default file na…'
complete -c ctags -s t --description 'option was omitted since the recognition of typedef s is now required for C s…'
complete -c ctags -s v --description 'If the.'

