# doas
# Autogenerated from man page /usr/share/man/man1/doas.1.gz
complete -c doas -s C --description 'Parse and check the configuration file config, then exit.'
complete -c doas -s L --description 'Clear any persisted authentications from previous invocations, then immediate…'
complete -c doas -s n --description 'Non interactive mode, fail if the matching rule doesn\'t have the nopass optio…'
complete -c doas -s s --description 'Execute the shell from SHELL or /etc/passwd.'
complete -c doas -s u --description 'Execute the command as user.  The default is root.'

