# fceux-net-server
# Autogenerated from man page /usr/share/man/man6/fceux-net-server.6.gz
complete -c fceux-net-server -s h --description 'Displays a help message.'
complete -c fceux-net-server -s v --description 'Displays the version number and quits.'
complete -c fceux-net-server -s p --description 'Starts server on given port; the default is 4046.'
complete -c fceux-net-server -s w --description 'Specifies a password for entry.'
complete -c fceux-net-server -s m --description 'Specifies the maximum number of clients allowed to access the server; the def…'
complete -c fceux-net-server -s t --description 'Specifies the number of seconds before the server times out; the default is 5.'
complete -c fceux-net-server -s f --description 'Specifies frame divisor, which controls the number of updates sent to client;…'
complete -c fceux-net-server -s c --description 'Loads the given configuration file.  The default is /etc/fceux-server. conf.'

