# fimgs
# Autogenerated from man page /usr/share/man/man1/fimgs.1.gz
complete -c fimgs -s m --description 'Dump a man page for fimgs.'
complete -c fimgs -s p --description 'Specify password for the \'gs\' -p (password) option.'
complete -c fimgs -s r --description 'Specify resolution for the \'gs\' -r option (e. g. : 96x96; default 120x120).'
complete -c fimgs -s h --description 'Will display a help message.'

