# git-lfs-install
# Autogenerated from man page /usr/share/man/man1/git-lfs-install.1.gz
complete -c git-lfs-install -l force --description 'Sets the "lfs" smudge and clean filters, overwriting existing values.'
complete -c git-lfs-install -l local --description 'Sets the "lfs" smudge and clean filters in the local repository\'s git config,…'
complete -c git-lfs-install -l worktree --description 'Sets the "lfs" smudge and clean filters in the current working tree\'s git con…'
complete -c git-lfs-install -l manual --description 'Print instructions for manually updating your hooks to include git-lfs functi…'
complete -c git-lfs-install -l system --description 'Sets the "lfs" smudge and clean filters in the system git config, e. g.'
complete -c git-lfs-install -l skip-smudge --description 'Skips automatic downloading of objects on clone or pull.'

