# git-lfs-locks
# Autogenerated from man page /usr/share/man/man1/git-lfs-locks.1.gz
complete -c git-lfs-locks -s r -l remote --description 'Specify the Git LFS server to use.  Ignored if the lfs. url config key is set.'
complete -c git-lfs-locks -s i -l id --description 'Specifies a lock by its ID.  Returns a single result.'
complete -c git-lfs-locks -s p -l path --description 'Specifies a lock by its path.  Returns a single result.'
complete -c git-lfs-locks -l local --description 'Lists only our own locks which are cached locally.  Skips a remote call.'
complete -c git-lfs-locks -l cached --description 'Lists cached locks from the last remote call.'
complete -c git-lfs-locks -l verify --description 'Verifies the lock owner on the server and marks our own locks by \'O\'.'
complete -c git-lfs-locks -s l -l limit --description 'Specifies number of results to return.'

