# git-lfs-checkout
# Autogenerated from man page /usr/share/man/man1/git-lfs-checkout.1.gz
complete -c git-lfs-checkout -l base --description 'Check out the merge base of the specified file.'
complete -c git-lfs-checkout -l ours --description 'Check out our side (that of the current branch) of the conflict for the speci…'
complete -c git-lfs-checkout -l theirs --description 'Check out their side (that of the other branch) of the conflict for the speci…'

