# git-lfs-lock
# Autogenerated from man page /usr/share/man/man1/git-lfs-lock.1.gz
complete -c git-lfs-lock -s r -l remote --description 'Specify the Git LFS server to use.  Ignored if the lfs. url config key is set.'

