# git-lfs-pointer
# Autogenerated from man page /usr/share/man/man1/git-lfs-pointer.1.gz
complete -c git-lfs-pointer -l file --description 'A local file to build the pointer from.'
complete -c git-lfs-pointer -l pointer --description 'A local file including the contents of a pointer generated from another imple…'
complete -c git-lfs-pointer -l stdin --description 'Reads the pointer from STDIN to compare with the pointer generated from --fil…'

