# git-lfs-uninstall
# Autogenerated from man page /usr/share/man/man1/git-lfs-uninstall.1.gz
complete -c git-lfs-uninstall -l local --description 'Removes the "lfs" smudge and clean filters from the local repository\'s git co…'
complete -c git-lfs-uninstall -l worktree --description 'Removes the "lfs" smudge and clean filters from the current working tree\'s gi…'
complete -c git-lfs-uninstall -l system --description 'Removes the "lfs" smudge and clean filters from the system git config, instea…'

