# git-lfs-prune
# Autogenerated from man page /usr/share/man/man1/git-lfs-prune.1.gz
complete -c git-lfs-prune -l dry-run -s d --description '.'
complete -c git-lfs-prune -l verify-remote -s c --description '.'
complete -c git-lfs-prune -l no-verify-remote --description '.'
complete -c git-lfs-prune -l verbose -s v --description '.'

