# git-lfs-fetch
# Autogenerated from man page /usr/share/man/man1/git-lfs-fetch.1.gz
complete -c git-lfs-fetch -s I -l include --description 'Specify lfs. fetchinclude just for this invocation; see INCLUDE AND EXCLUDE .'
complete -c git-lfs-fetch -s X -l exclude --description 'Specify lfs. fetchexclude just for this invocation; see INCLUDE AND EXCLUDE .'
complete -c git-lfs-fetch -l recent --description 'Download objects referenced by recent branches & commits in addition to those…'
complete -c git-lfs-fetch -l all --description 'Download all objects that are referenced by any commit reachable from the ref…'

