# git-lfs-clone
# Autogenerated from man page /usr/share/man/man1/git-lfs-clone.1.gz
complete -c git-lfs-clone -s I -l include --description 'See INCLUDE AND EXCLUDE .'
complete -c git-lfs-clone -s X -l exclude --description 'See INCLUDE AND EXCLUDE .'

