# git-lfs-status
# Autogenerated from man page /usr/share/man/man1/git-lfs-status.1.gz
complete -c git-lfs-status -l porcelain --description 'Give the output in an easy-to-parse format for scripts.'

