# hello_xr
# Autogenerated from man page /usr/share/man/man1/hello_xr.1.gz
complete -c hello_xr -s h --description 'Show brief usage instructions.'
complete -c hello_xr -o ff --description 'Specify the form factor to use.'
complete -c hello_xr -o vc --description 'Specify the view configuration to use.'
complete -c hello_xr -o bm --description 'Specify the environment blend mode to use.'
complete -c hello_xr -s s --description 'Specify the space to use.'
complete -c hello_xr -s v --description 'Enable verbose logging output from the hello_xr application itself.'

