# jar-openjdk11
# Autogenerated from man page /usr/share/man/man1/jar-openjdk11.1.gz
complete -c jar-openjdk11 -s C --description 'br When creating (\\f3c) or updating (\\f3u) a JAR file, this option temporaril…'
complete -c jar-openjdk11 -o Joption --description 'Sets the specified JVM option to be used when the JRE runs the JAR file.'

