# jcmd-openjdk11
# Autogenerated from man page /usr/share/man/man1/jcmd-openjdk11.1.gz
complete -c jcmd-openjdk11 -s f --description 'Reads commands from the specified file.'
complete -c jcmd-openjdk11 -o 'h
.br
-help' --description 'Prints a help message.'
complete -c jcmd-openjdk11 -s l --description 'Prints the list of running Java processes identifiers with the main class and…'
complete -c jcmd-openjdk11 -s h --description 'or.'
complete -c jcmd-openjdk11 -o help --description 'option prints the tool\'s help message.'

