# jdb-openjdk11
# Autogenerated from man page /usr/share/man/man1/jdb-openjdk11.1.gz
complete -c jdb-openjdk11 -o help --description 'br Displays a help message.'
complete -c jdb-openjdk11 -o sourcepath --description 'br Uses the specified path to search for source files in the specified path.'
complete -c jdb-openjdk11 -o attach --description 'br Attaches the debugger to a running JVM with the default connection mechani…'
complete -c jdb-openjdk11 -o listen --description 'br Waits for a running JVM to connect to the specified address with a standar…'
complete -c jdb-openjdk11 -o launch --description 'br Starts the debugged application immediately upon startup of JDB.'
complete -c jdb-openjdk11 -o listconnectors --description 'br List the connectors available in this JVM.'
complete -c jdb-openjdk11 -o connect --description 'br Connects to the target JVM with the named connector and listed argument va…'
complete -c jdb-openjdk11 -o dbgtrace --description 'br Prints information for debugging the \\f3jdb command.'
complete -c jdb-openjdk11 -o tclient --description 'br Runs the application in the Java HotSpot VM client.'
complete -c jdb-openjdk11 -o tserver --description 'br Runs the application in the Java HotSpot VM server.'
complete -c jdb-openjdk11 -o Joption --description '.'
complete -c jdb-openjdk11 -s v -o 'verbose[:class' --description '.'
complete -c jdb-openjdk11 -o Dname --description '.'
complete -c jdb-openjdk11 -o classpath --description '.'
complete -c jdb-openjdk11 -o Xoption --description '.'

