# jinfo-openjdk11
# Autogenerated from man page /usr/share/man/man1/jinfo-openjdk11.1.gz
complete -c jinfo-openjdk11 -o flag --description 'br Prints the name and value of the specified command-line flag.'
complete -c jinfo-openjdk11 -o ']name' --description 'br enables or disables the specified Boolean command-line flag.'
complete -c jinfo-openjdk11 -o flags --description 'br Prints command-line flags passed to the JVM.'
complete -c jinfo-openjdk11 -o sysprops --description 'br Prints Java system properties as name-value pairs.'
complete -c jinfo-openjdk11 -s h --description 'br Prints a help message.'
complete -c jinfo-openjdk11 -o help --description '.'

