# jstack-openjdk11
# Autogenerated from man page /usr/share/man/man1/jstack-openjdk11.1.gz
complete -c jstack-openjdk11 -s F --description 'br Force a stack dump when \\f3jstack [\\f3-l] \\f3pid does not respond.'
complete -c jstack-openjdk11 -s l --description 'br Long listing.'
complete -c jstack-openjdk11 -s m --description 'br Prints a mixed mode stack trace that has both Java and native C/C++ frames.'
complete -c jstack-openjdk11 -s h --description 'br Prints a help message.'
complete -c jstack-openjdk11 -o help --description '.'

