# kccachetest
# Autogenerated from man page /usr/share/man/man1/kccachetest.1.gz
complete -c kccachetest -o th --description '.'
complete -c kccachetest -o rnd --description '.'
complete -c kccachetest -o etc --description '.'
complete -c kccachetest -o tran --description '.'
complete -c kccachetest -o tc --description '.'
complete -c kccachetest -o bnum --description '.'
complete -c kccachetest -o capcnt --description '.'
complete -c kccachetest -o capsiz --description '.'
complete -c kccachetest -o lv --description '.'
complete -c kccachetest -o it --description 'This command returns 0 on success, another on failure.'

