# kcgrasstest
# Autogenerated from man page /usr/share/man/man1/kcgrasstest.1.gz
complete -c kcgrasstest -o th --description '.'
complete -c kcgrasstest -o rnd --description '.'
complete -c kcgrasstest -o etc --description '.'
complete -c kcgrasstest -o tran --description '.'
complete -c kcgrasstest -o tc --description '.'
complete -c kcgrasstest -o bnum --description '.'
complete -c kcgrasstest -o psiz --description '.'
complete -c kcgrasstest -o pccap --description '.'
complete -c kcgrasstest -o rcd --description '.'
complete -c kcgrasstest -o rcld --description '.'
complete -c kcgrasstest -o rcdd --description '.'
complete -c kcgrasstest -o lv --description '.'
complete -c kcgrasstest -o it --description 'This command returns 0 on success, another on failure.'

