# kclangctest
# Autogenerated from man page /usr/share/man/man1/kclangctest.1.gz
complete -c kclangctest -o rnd --description '.'
complete -c kclangctest -o etc --description '.'
complete -c kclangctest -o tran --description '.'
complete -c kclangctest -o oat --description '.'
complete -c kclangctest -o oas --description '.'
complete -c kclangctest -o onl --description '.'
complete -c kclangctest -o otl --description '.'
complete -c kclangctest -o onr --description '.'
complete -c kclangctest -o bnum --description 'This command returns 0 on success, another on failure.'

