# kcprototest
# Autogenerated from man page /usr/share/man/man1/kcprototest.1.gz
complete -c kcprototest -o tree --description '.'
complete -c kcprototest -o th --description '.'
complete -c kcprototest -o rnd --description '.'
complete -c kcprototest -o etc --description '.'
complete -c kcprototest -o tran --description '.'
complete -c kcprototest -o it --description 'This command returns 0 on success, another on failure.'

