# kcstashtest
# Autogenerated from man page /usr/share/man/man1/kcstashtest.1.gz
complete -c kcstashtest -o th --description '.'
complete -c kcstashtest -o rnd --description '.'
complete -c kcstashtest -o etc --description '.'
complete -c kcstashtest -o tran --description '.'
complete -c kcstashtest -o bnum --description '.'
complete -c kcstashtest -o lv --description '.'
complete -c kcstashtest -o it --description 'This command returns 0 on success, another on failure.'

