# kcutiltest
# Autogenerated from man page /usr/share/man/man1/kcutiltest.1.gz
complete -c kcutiltest -o th --description '.'
complete -c kcutiltest -o iv --description '.'
complete -c kcutiltest -o rnd --description '.'
complete -c kcutiltest -o msiz --description '.'
complete -c kcutiltest -o bnum --description 'This command returns 0 on success, another on failure.'

