# lolcat
# Autogenerated from man page /usr/share/man/man6/lolcat.6.gz
complete -c lolcat -s p -l spread --description 'Inclination of the rainbow stripes .'
complete -c lolcat -s F -l freq --description 'Frequency of the rainbow effect. br (low values around 0.'
complete -c lolcat -s S -l seed --description 'Initial value for the random number generator; 0 means automatic.'
complete -c lolcat -s a -l animate --description 'Fade every line through an animation before printing the next one.'
complete -c lolcat -s d -l duration --description 'Duration of the animation.'
complete -c lolcat -s s -l speed --description 'Speed of the animation. br (frame rate, ie.'
complete -c lolcat -s i -l invert --description 'Inverts the background and foreground colors.'
complete -c lolcat -s t -l truecolor --description 'Enables 24-bit truecolor mode.'
complete -c lolcat -s f -l force --description 'Force color even when stdout is not a tty.'
complete -c lolcat -s v -l version --description 'Shows lolcat version.'
complete -c lolcat -s h -l help --description 'Shows options summary.'

