# nethogs
# Autogenerated from man page /usr/share/man/man8/nethogs.8.gz
complete -c nethogs -s h --description 'display available commands usage.'
complete -c nethogs -s V --description 'print version info.'
complete -c nethogs -s d --description 'delay for refresh rate.'
complete -c nethogs -s v --description 'select view mode.'
complete -c nethogs -s p --description 'sniff in promiscuous mode (not recommended).'
complete -c nethogs -s a --description 'monitor all devices, even loopback/stopped ones.'
complete -c nethogs -s t --description 'tracemode.'
complete -c nethogs -s c --description 'limit number of refreshes.'
complete -c nethogs -s s --description 'sort by traffic sent.'
complete -c nethogs -s l --description 'display command line.'

