# nordvpn
# Autogenerated from man page /usr/share/man/man1/nordvpn.1.gz
complete -c nordvpn -l help -s h --description 'Display syntax for the given operation.'
complete -c nordvpn -l version -s v --description 'Display version and exit.'

