# notmuch-insert
# Autogenerated from man page /usr/share/man/man1/notmuch-insert.1.gz
complete -c notmuch-insert -l folder --description 'Deliver the message to the specified folder, relative to the top-level direct…'
complete -c notmuch-insert -l create-folder --description 'Try to create the folder named by the --folder option, if it does not exist.'
complete -c notmuch-insert -l keep --description 'Keep the message file if indexing fails, and keep the message indexed if appl…'
complete -c notmuch-insert -l no-hooks --description 'Prevent hooks from being run.'
complete -c notmuch-insert -l world-readable --description 'When writing mail to the mailbox, allow it to be read by users other than the…'
complete -c notmuch-insert -l decrypt --description 'If true and the message is encrypted, try to decrypt the message while indexi…'

