# notmuch-tag
# Autogenerated from man page /usr/share/man/man1/notmuch-tag.1.gz
complete -c notmuch-tag -l remove-all --description 'Remove all tags from each message matching the search terms before applying t…'
complete -c notmuch-tag -l batch --description 'Read batch tagging operations from a file (stdin by default).'
complete -c notmuch-tag -l input --description 'Read input from given file, instead of from stdin.  Implies.'

