# notmuch-new
# Autogenerated from man page /usr/share/man/man1/notmuch-new.1.gz
complete -c notmuch-new -l no-hooks --description 'Prevents hooks from being run.'
complete -c notmuch-new -l quiet --description 'Do not print progress or results.'
complete -c notmuch-new -l verbose --description 'Print file names being processed.  Ignored when combined with --quiet.'
complete -c notmuch-new -l decrypt --description 'If true, when encountering an encrypted message, try to decrypt it while inde…'
complete -c notmuch-new -l full-scan --description 'By default notmuch-new uses directory modification times (mtimes) to optimize…'

