# notmuch-setup
# Autogenerated from man page /usr/share/man/man1/notmuch-setup.1.gz
complete -c notmuch-setup -l help --description 'Print a synopsis of available commands and exit.'
complete -c notmuch-setup -l version --description 'Print the installed version of notmuch, and exit.'
complete -c notmuch-setup -l config --description 'Specify the configuration file to use.'
complete -c notmuch-setup -l uuid --description 'Enforce that the database UUID (a unique identifier which persists until e. g.'

