# notmuch
# Autogenerated from man page /usr/share/man/man1/notmuch.1.gz
complete -c notmuch -l help --description 'Print a synopsis of available commands and exit.'
complete -c notmuch -l version --description 'Print the installed version of notmuch, and exit.'
complete -c notmuch -l config --description 'Specify the configuration file to use.'
complete -c notmuch -l uuid --description 'Enforce that the database UUID (a unique identifier which persists until e. g.'

