# notmuch-search
# Autogenerated from man page /usr/share/man/man1/notmuch-search.1.gz
complete -c notmuch-search -l format --description 'Presents the results in either JSON, S-Expressions, newline character separat…'
complete -c notmuch-search -l format-version --description 'Use the specified structured output format version.'
complete -c notmuch-search -l output --description 'NDENT 7. 0.'
complete -c notmuch-search -l sort --description 'This option can be used to present results in either chronological order (old…'
complete -c notmuch-search -l offset --description 'Skip displaying the first N results.'
complete -c notmuch-search -l limit --description 'Limit the number of displayed results to N.'
complete -c notmuch-search -l exclude --description 'A message is called "excluded" if it matches at least one tag in search.'
complete -c notmuch-search -l duplicate --description 'For --output=files, output the Nth filename associated with each message matc…'

