# notmuch-reply
# Autogenerated from man page /usr/share/man/man1/notmuch-reply.1.gz
complete -c notmuch-reply -l format --description 'NDENT 7. 0.'
complete -c notmuch-reply -l format-version --description 'Use the specified structured output format version.'
complete -c notmuch-reply -l reply-to --description 'NDENT 7. 0.'
complete -c notmuch-reply -l decrypt --description 'If true, decrypt any MIME encrypted parts found in the selected content (i. e.'

