# notmuch-count
# Autogenerated from man page /usr/share/man/man1/notmuch-count.1.gz
complete -c notmuch-count -l output --description 'NDENT 7. 0.'
complete -c notmuch-count -l exclude --description 'Specify whether to omit messages matching search.'
complete -c notmuch-count -l batch --description 'Read queries from a file (stdin by default), one per line, and output the num…'
complete -c notmuch-count -l lastmod --description 'Append lastmod (counter for number of database updates) and UUID to the outpu…'
complete -c notmuch-count -l input --description 'Read input from given file, instead of from stdin.  Implies.'

