# notmuch-dump
# Autogenerated from man page /usr/share/man/man1/notmuch-dump.1.gz
complete -c notmuch-dump -l gzip --description 'Compress the output in a format compatible with gzip(1).'
complete -c notmuch-dump -l format --description 'Notmuch restore supports two plain text dump formats, both with one message-i…'
complete -c notmuch-dump -l include --description 'Control what kind of metadata is included in the output.  NDENT 7. 0.'
complete -c notmuch-dump -l output --description 'Write output to given file instead of stdout.'

