# notmuch-address
# Autogenerated from man page /usr/share/man/man1/notmuch-address.1.gz
complete -c notmuch-address -l format --description 'Presents the results in either JSON, S-Expressions, newline character separat…'
complete -c notmuch-address -l format-version --description 'Use the specified structured output format version.'
complete -c notmuch-address -l output --description 'Controls which information appears in the output.'
complete -c notmuch-address -l deduplicate --description 'Control the deduplication of results.  NDENT 7. 0.'
complete -c notmuch-address -l sort --description 'This option can be used to present results in either chronological order (old…'
complete -c notmuch-address -l exclude --description 'A message is called "excluded" if it matches at least one tag in search.'

