# notmuch-emacs-mua
# Autogenerated from man page /usr/share/man/man1/notmuch-emacs-mua.1.gz
complete -c notmuch-emacs-mua -s h -l help --description 'Display help.'
complete -c notmuch-emacs-mua -s s -l subject --description 'Specify the subject of the message.'
complete -c notmuch-emacs-mua -l to --description 'Specify a recipient (To).'
complete -c notmuch-emacs-mua -s c -l cc --description 'Specify a carbon-copy (Cc) recipient.'
complete -c notmuch-emacs-mua -s b -l bcc --description 'Specify a blind-carbon-copy (Bcc) recipient.'
complete -c notmuch-emacs-mua -s i -l body --description 'Specify a file to include into the body of the message.'
complete -c notmuch-emacs-mua -l hello --description 'Go to the Notmuch hello screen instead of the message composition window if n…'
complete -c notmuch-emacs-mua -l no-window-system --description 'Even if a window system is available, use the current terminal.'
complete -c notmuch-emacs-mua -l client --description 'Use emacsclient, rather than emacs.'
complete -c notmuch-emacs-mua -l auto-daemon --description 'Automatically start Emacs in daemon mode, if the Emacs server is not running.'
complete -c notmuch-emacs-mua -l create-frame --description 'Create a new frame instead of trying to use the current Emacs frame.'
complete -c notmuch-emacs-mua -l print --description 'Output the resulting elisp to stdout instead of evaluating it.'

