# openrazer-daemon
# Autogenerated from man page /usr/share/man/man8/openrazer-daemon.8.gz
complete -c openrazer-daemon -s v -l verbose --description '.'
complete -c openrazer-daemon -s F -l foreground --description '.'
complete -c openrazer-daemon -s r -l respawn --description '.'
complete -c openrazer-daemon -s s -l stop --description '.'
complete -c openrazer-daemon -l as-root --description '.'
complete -c openrazer-daemon -l config --description '.'
complete -c openrazer-daemon -l run-dir --description '.'
complete -c openrazer-daemon -l log-dir --description '.'
complete -c openrazer-daemon -l test-dir --description '.'

