# playonlinux
# Autogenerated from man page /usr/share/man/man1/playonlinux.1.gz
complete -c playonlinux -l version --description 'Show version number and exit.'
complete -c playonlinux -l run --description ' Run directly the specified program.'

