# playonlinux-pkg
# Autogenerated from man page /usr/share/man/man1/playonlinux-pkg.1.gz
complete -c playonlinux-pkg -s b -l browse --description 'Choose a file.'
complete -c playonlinux-pkg -s e -l extract --description 'Extract the package.'
complete -c playonlinux-pkg -s i -l install --description 'Install the package.'
complete -c playonlinux-pkg -s h -l help --description ' Show usage.'

