# readtags
# Autogenerated from man page /usr/share/man/man1/readtags.1.gz
complete -c readtags -s t -l tag-file --description 'Use specified tag file (default: "tags").'
complete -c readtags -o 's[0' -l override-sort-detection --description 'Override sort detection of tag file.  METHOD: unsorted|sorted|foldcase.'
complete -c readtags -s i -l icase-match --description 'Perform case-insensitive matching in the NAME action.'
complete -c readtags -s p -l prefix-match --description 'Perform prefix matching in the NAME action.'
complete -c readtags -s d -l debug --description 'Turn on debugging output.'
complete -c readtags -s E -l escape-output --description 'Escape characters like tabs in output as described in tags(5).'
complete -c readtags -s e -l extension-fields --description 'Include extension fields in output.'
complete -c readtags -s n -l line-number --description 'Also include the line number field when -e option is give.'
complete -c readtags -s Q -l filter --description 'Filter the tags listed by ACTION with EXP before printing.'
complete -c readtags -s S -l sorter --description 'Sort the tags listed by ACTION with EXP before printing.'
complete -c readtags -s l -l list --description 'List regular tags.'
complete -c readtags -s D -l list-pseudo-tags --description 'Equivalent to --list-pseudo-tags.'
complete -c readtags -s 1 --description 'file: $ readtags -S \'(<or> (<> $input &input) (<> $line &line))\' -l The *- op…'

