# renice
# Autogenerated from man page /usr/share/man/man1/renice.1p.gz
complete -c renice -o nincrement --description 'Specify how the nice value of the specified process or processes is to be adj…'

