# topgrade
# Autogenerated from man page /usr/share/man/man8/topgrade.8.gz
complete -c topgrade -l only --description 'Run specific steps . RS . RE.'
complete -c topgrade -l disable --description 'Disable specific steps . RS . RE.'
complete -c topgrade -s c -l cleanup --description 'Cleanup temporary or old files . RS . RE.'
complete -c topgrade -s n -l dry-run --description 'Outputs steps simulation . RS . RE.'
complete -c topgrade -l edit-config --description 'Edit the configuration file . RS . RE.'
complete -c topgrade -s h -l help --description 'Prints help information . RS . RE.'
complete -c topgrade -s k -l keep --description 'Prompt for a key before exiting . RS . RE.'
complete -c topgrade -l no-retry --description 'Do not ask to retry failed steps . RS . RE.'
complete -c topgrade -s t -l tmux --description 'Run inside tmux . RS . RE.'
complete -c topgrade -s V -l version --description 'Prints version information . RS . RE.'
complete -c topgrade -s v -l verbose --description 'Output logs.'
complete -c topgrade -s y -l yes --description 'Say yes to package manager\'s prompt (experimental).'

