# trickled
# Autogenerated from man page /usr/share/man/man8/trickled.8.gz
complete -c trickled -s v --description 'Increases the verbosity level (can be specified multiple times).'
complete -c trickled -s V --description 'Prints version.'
complete -c trickled -s f --description 'Runs trickled in the foreground.'
complete -c trickled -s s --description 'Uses syslog for all output (instead of stderr).'
complete -c trickled -s d --description 'Limit the download bandwidth consumption to rate KB/s.'
complete -c trickled -s u --description 'Limit the upload bandwidth consumption to rate KB/s.'
complete -c trickled -s t --description 'Set smoothing time to seconds s.'
complete -c trickled -s l --description 'Set smoothing length to length KB.'
complete -c trickled -s p --description 'Set default priority to priority.'
complete -c trickled -s c --description 'Use the configuration file file.'
complete -c trickled -s n --description 'Set socket name to path.  By default, trickled uses /tmp/. trickled. sock.'
complete -c trickled -s N --description 'Notifies user of total bandwidth consumption every seconds s.'
complete -c trickled -s w --description 'Set peak detection window size to size KB.'

