# vi
# Autogenerated from man page /usr/share/man/man1/vi.1p.gz
complete -c vi -o ccommand --description 'See the R ex command description of the  -c option.'
complete -c vi -s r --description 'See the R ex command description of the  -r option.'
complete -c vi -s R --description 'See the R ex command description of the  -R option.'
complete -c vi -o ttagstring --description 'See the R ex command description of the  -t option.'
complete -c vi -s c --description 'See the ex command description of the.'
complete -c vi -s t --description 'See the ex command description of the.'
complete -c vi -s w --description 'See the ex command description of the.'
complete -c vi -s 1 --description 'error.   b.'
complete -c vi -s 2 --description 'follows, and the window edit option shall not be affected.'
complete -c vi -s D --description 'can result in a completely changed screen, without any overlap.'

