# vimb
# Autogenerated from man page /usr/share/man/man1/vimb.1.gz
complete -c vimb -s C -l cmd --description 'Run CMD as ex command line right before the first page is loaded.'
complete -c vimb -s c -l config --description 'Use custom configuration given as FILE.'
complete -c vimb -s e -l embed --description 'WINID of an XEmbed-aware application, that Vimb will use as its parent.'
complete -c vimb -s i -l incognito --description 'Start an instance with user data read-only (see FILES section).'
complete -c vimb -s h -l help --description 'Show help options.'
complete -c vimb -s p -l profile --description 'Create or open specified configuration profile.'
complete -c vimb -s v -l version --description 'Print build and version information and then quit.'
complete -c vimb -l no-maximize --description 'Do no attempt to maximize window.'
complete -c vimb -l bug-info --description 'Prints information about used libraries for bug reports and then quit.'

