# virt-manager
# Autogenerated from man page /usr/share/man/man1/virt-manager.1.gz
complete -c virt-manager -s h -l help --description 'Display command line help summary.'
complete -c virt-manager -l version --description 'Show virt-manager\\(aqs version number and exit.'
complete -c virt-manager -s c -l connect --description 'Specify the hypervisor connection URI.'
complete -c virt-manager -l debug --description 'List debugging output to the console (normally this is only logged in ~/.'
complete -c virt-manager -l no-fork --description 'Don\\(aqt fork virt-manager off into the background: run it blocking the curre…'
complete -c virt-manager -l show-domain-creator --description 'Display the wizard for creating new virtual machines.'
complete -c virt-manager -l show-domain-editor --description 'Display the dialog for editing properties of the virtual machine with unique …'
complete -c virt-manager -l show-domain-performance --description 'Display the dialog for monitoring performance of the virtual machine with uni…'
complete -c virt-manager -l show-domain-console --description 'Display the virtual console of the virtual machine with unique ID matching ei…'
complete -c virt-manager -l show-host-summary --description 'Display the host/connection details window.'

