# vmware
# Autogenerated from man page /usr/share/man/man1/vmware.1.gz
complete -c vmware -s s --description 'Set the configuration variable \\fIname\\fP to \\fIvalue\\fP, overriding other de…'
complete -c vmware -s n --description 'Open a new window.'
complete -c vmware -s t --description 'Open a virtual machine or team in a new tab in an existing window.'
complete -c vmware -s x --description 'Power on the virtual machine on startup.'
complete -c vmware -s X --description 'Power on and switch to full screen mode.'
complete -c vmware -s q --description 'Attempt to exit the virtual machine after powering off.'
complete -c vmware -s v --description 'Display the program version and exit without starting a virtual machine.'
complete -c vmware -s W --description 'Starts a second instance of Workstation in a different X server.'

