# xte
# Autogenerated from man page /usr/share/man/man1/xte.1.gz
complete -c xte -s i --description 'XInput 2. x device to use.  List devices with \'xinput list\'.'
complete -c xte -s x --description 'Send commands to remote X server.'
complete -c xte -l help -s h --description 'Show summary of options.  COMMANDS.'

