#! /bin/sh

sxhkd &
picom &
nitrogen --restore &
$HOME/.config/polybar/launch.sh
setxkbmap -layout workman
xmodmap ~/.Xmodmap
wal -Rn &
xset m 2/1 0

bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config click_to_focus button1
